### ISSUE TITLE
Tutorial error in the "water/nvt" process (nvt_grompp.log: Fatal error: Invalid atom number 3780 in indexfile)

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [luancarvalhomartins/PyAutoFEP#135]
Hi,
   I failed in the "bash runall.sh" step. The protein file worked well but the water file failed in the nvt process.
   Here are the details in nvt_grompp.log.
   

> Command line:
>   gmx_mpi grompp -c FXR_12-FXR_74/water/lambda0/nve/nve.gro -r FXR_12-FXR_74/water/lambda0/nve/nve.gro -f FXR_12-FXR_74/water/lambda0/nvt/nvt.mdp -p FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top -o FXR_12-FXR_74/water/lambda0/nvt/nvt.tpr -n /lustre/home/jlu/software/pyautofep/t/tutorial/FXR_12-FXR_74/protein/build_system_111129_01032024/index.ndx -po FXR_12-FXR_74/water/lambda0/nvt/nvt_mdout.mdp -maxwarn 3
> 
> Replacing old mdp entry 'nstxtcout' by 'nstxout-compressed'
> Setting the LD random seed to -885178379
> Generated 449826 of the 449826 non-bonded parameter combinations
> Generating 1-4 interactions: fudge = 0.5
> Generated 449826 of the 449826 1-4 parameter combinations
> Excluding 3 bonded neighbours molecule type 'LIG'
> turning H bonds into constraints...
> Excluding 2 bonded neighbours molecule type 'SOL'
> turning H bonds into constraints...
> Excluding 1 bonded neighbours molecule type 'NA'
> turning H bonds into constraints...
> Warning: atom name 1 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (O00_const_idx1 - O00_c)
> Warning: atom name 2 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C01_const_idx2 - C01_c)
> Warning: atom name 3 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (O02_const_idx3 - O02_c)
> Warning: atom name 4 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C03_const_idx4 - C03_c)
> Warning: atom name 5 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C04_const_idx5 - C04_c)
> Warning: atom name 6 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C05_const_idx6 - C05_c)
> Warning: atom name 7 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C06_const_idx7 - C06_c)
> Warning: atom name 8 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C07_const_idx8 - C07_c)
> Warning: atom name 9 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (N08_const_idx9 - N08_c)
> Warning: atom name 10 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C09_const_idx10 - C09_c)
> Warning: atom name 11 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (O0A_const_idx11 - O0A_c)
> Warning: atom name 12 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C0B_const_idx12 - C0B_c)
> Warning: atom name 13 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C0C_const_idx13 - C0C_c)
> Warning: atom name 14 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C0D_const_idx14 - C0D_c)
> Warning: atom name 15 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (N0E_const_idx15 - N0E_c)
> Warning: atom name 16 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C0F_const_idx16 - C0F_c)
> Warning: atom name 17 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (C0G_const_idx17 - C0G_c)
> Warning: atom name 18 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (S0H_const_idx18 - S0H_c)
> Warning: atom name 19 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (O0I_const_idx19 - O0I_c)
> Warning: atom name 20 in FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top and FXR_12-FXR_74/water/lambda0/nve/nve.gro does not match (O0J_const_idx20 - O0J_c)
> (more than 20 non-matching atom names)
> 
> WARNING 1 [file fullsystem_111141_01032024.top, line 55]:
>   58 non-matching atom names
>   atom names from
>   FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top will be
>   used
>   atom names from FXR_12-FXR_74/water/lambda0/nve/nve.gro will be ignored
> 
> 
> Cleaning up constraints and constant bonded interactions with virtual sites
> Removing all charge groups because cutoff-scheme=Verlet
> 
> -------------------------------------------------------
> Program:     gmx grompp, version 2019.3
> Source file: src/gromacs/gmxpreprocess/readir.cpp (line 2661)
> 
> Fatal error:
> Invalid atom number 3780 in indexfile
> 
> For more information and tips for troubleshooting, please check the GROMACS
> website at http://www.gromacs.org/Documentation/Errors
> -------------------------------------------------------
> application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
> [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
> :
> system msg for write_line failure : Bad file descriptor
> 

  After check, I found it's due to the wrong index file （protein/..)
>   gmx_mpi grompp -c FXR_12-FXR_74/water/lambda0/nve/nve.gro -r FXR_12-FXR_74/water/lambda0/nve/nve.gro -f FXR_12-FXR_74/water/lambda0/nvt/nvt.mdp -p FXR_12-FXR_74/water/lambda0/nvt/../fullsystem_111141_01032024.top -o FXR_12-FXR_74/water/lambda0/nvt/nvt.tpr -n /lustre/home/jlu/software/pyautofep/t/tutorial/FXR_12-FXR_74/**### protein/build_system_111129_01032024**/index.ndx -po FXR_12-FXR_74/water/lambda0/nvt/nvt_mdout.mdp -maxwarn 3

  Can you help us solve this problem. Thanks.

Jiang

**Comment by YumizSui** [comment]
I encountered the same problem.
It seems that the implementation of the path to the index file provided for the water system in `prepare_dual_topology.py` is incorrect.
For example, in `runall_FXR_12-FXR_74_water.sh`, `tutorial/FXR_12-FXR_74/protein/build_system_*/index.ndx` is specified, but this should actually specify `tutorial/FXR_12-FXR_74/water/build_water_*/index.ndx`.

**Comment by Jiang-Lu-CAS** [comment]
> I encountered the same problem. It seems that the implementation of the path to the index file provided for the water system in `prepare_dual_topology.py` is incorrect. For example, in `runall_FXR_12-FXR_74_water.sh`, `tutorial/FXR_12-FXR_74/protein/build_system_*/index.ndx` is specified, but this should actually specify `tutorial/FXR_12-FXR_74/water/build_water_*/index.ndx`.

@YumizSui Yes, I corrected it by hand and it worked after I replace the protein index to the right water index. Unfortunately, it failed again in the analysis step, which looked like the water file missed several code compared with the protein run file. The author should correct the code. Have you run it completely? How did you solve the problems? Thanks.

**Comment by TIAN298** [comment]
Hello, I encountered with same problems, and I think it is related with command lines from "tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh" , which is generated from prepare_dual_topology.py. But I still cannot get it right, I wonder have you guys solved this problem?
